# Generated by Django 2.1 on 2018-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NashBitesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
